name: CityTaster Deploy

on:
  push:
    branches: [main]            # Deploy only on main branch changes
  workflow_dispatch:            # Allow manual triggering from the GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    # ---------------------------------------------------------
    # Job-level environment variables
    # ---------------------------------------------------------
    env:
      AWS_REGION: us-east-1                 # The AWS region for all AWS actions in this workflow
      ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
        # ECR registry URL; use the correct AWS region here
      DB_NAME: CityTasterDB                 # MongoDB database name, if needed in scripts

    steps:
      # --- Checkout code from repo ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- (No Buildx setup needed for classic Docker builds) ---

      # --- Configure AWS credentials for AWS CLI and ECR ---
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # --- Login to Amazon ECR (Elastic Container Registry) ---
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # --- Build and push backend Docker image to ECR ---
      - name: Build and push backend Docker image
        run: |
          docker build -t $ECR_REGISTRY/citytaster-backend:latest ./backend
          docker push $ECR_REGISTRY/citytaster-backend:latest

      # --- Build and push frontend Docker image to ECR ---
      - name: Build and push frontend Docker image
        run: |
          docker build -t $ECR_REGISTRY/citytaster-frontend:latest ./frontend
          docker push $ECR_REGISTRY/citytaster-frontend:latest

      # --- Sync CSV data folder to S3 (must set S3_BUCKET_NAME as a secret) ---
      - name: Sync data folder to S3
        run: |
          aws s3 sync ./data s3://${{ secrets.S3_BUCKET_NAME }}/data

      # --- SSH into EC2 and redeploy Docker Compose stack ---
      # NOTE: Add the following repo secrets: EC2_PUBLIC_IP, EC2_SSH_KEY, S3_BUCKET_NAME, AWS_ACCOUNT_ID
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Go to your app directory (update as needed)
            cd app || cd ~/app || mkdir -p app && cd app

            # Sync latest data from S3
            aws s3 sync s3://${{ secrets.S3_BUCKET_NAME }}/data ./data

            # Login to ECR
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

            # Pull and redeploy latest containers
            docker-compose pull
            docker-compose up -d

            # (Optional) Clean up old/dangling Docker images
            docker image prune -af

# -------------------------------------------------------------
# IMPORTANT:
#   - All sensitive info should be set as repository or org secrets, not committed!
#   - The region in ECR_REGISTRY must match AWS_REGION.
#   - Never hardcode sensitive keys, secrets, or private SSH keys in this file.
# -------------------------------------------------------------

