# FILE: .github/workflows/infra-cdktf.yml
# Purpose: CI/CD pipeline for your infra + app images.
# - Uses GitHub OIDC to assume an AWS IAM role (no long-lived keys).
# - Builds & pushes Docker images (backend / frontend) to ECR.
# - Validates your config (VPC/Subnets/SGs) before any infra changes.
# - Synthesizes & deploys the selected CDKTF stack (dev by default).
#
# Safe-by-default:
# - On push to main: deploys DEV only.
# - On manual run: you can choose DEV or PROD (prod is a placeholder until you enable it).
#
# Prereqs:
# - Repo secret: DEPLOY_ROLE_ARN (IAM role ARN that trusts GitHub OIDC).
# - Your repo contains:
#   - infra/cdktf-app/my-cdktf/ (CDKTF app)
#   - scripts/validate-dev.cjs (config validator)
#   - scripts/print-ec2.cjs (post-deploy EC2 DNS helper)
#   - backend/Dockerfile, frontend/Dockerfile (image builds)

name: infra-cdktf

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      env:
        description: Environment to deploy
        type: choice
        required: true
        default: dev
        options: [dev, prod]
      build_images:
        description: Build & push Docker images first?
        type: boolean
        required: true
        default: true

env:
  AWS_REGION: us-east-1
  APP_ROOT: infra/cdktf-app/my-cdktf
  PROJECT: citytaster

jobs:
  deploy:
    name: Deploy (${{ github.event_name == 'workflow_dispatch' && inputs.env || 'dev' }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.event_name == 'workflow_dispatch' && inputs.env || 'dev' }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve environment (dev/prod)
        id: env
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            ENV="${{ inputs.env }}"
          else
            ENV="dev"
          fi
          echo "env_name=$ENV" >> "$GITHUB_OUTPUT"
          echo "STACK_NAME=${{ env.PROJECT }}-$ENV" >> "$GITHUB_OUTPUT"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build & push images unless manual run with build_images=false
      - name: Build & push backend image
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.build_images }}
        shell: bash
        run: |
          ENV="${{ steps.env.outputs.env_name }}"
          BACKEND_URI="${{ steps.ecr.outputs.registry }}/${{ env.PROJECT }}-${ENV}-backend"
          echo "Building $BACKEND_URI:latest"
          docker build -f backend/Dockerfile -t "$BACKEND_URI:latest" backend
          docker push "$BACKEND_URI:latest"

      - name: Build & push frontend image
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.build_images }}
        shell: bash
        run: |
          ENV="${{ steps.env.outputs.env_name }}"
          FRONTEND_URI="${{ steps.ecr.outputs.registry }}/${{ env.PROJECT }}-${ENV}-frontend"
          echo "Building $FRONTEND_URI:latest"
          docker build -f frontend/Dockerfile -t "$FRONTEND_URI:latest" frontend
          docker push "$FRONTEND_URI:latest"

      - name: Install CDKTF dependencies
        working-directory: ${{ env.APP_ROOT }}
        run: |
          npm ci
          npx cdktf provider add "aws@~> 5.0"

      - name: Validate ${{ steps.env.outputs.env_name }} config
        working-directory: ${{ env.APP_ROOT }}
        env:
          CTX_ENV: ${{ steps.env.outputs.env_name }}
        run: node scripts/validate-dev.cjs

      - name: Synthesize CDKTF
        working-directory: ${{ env.APP_ROOT }}
        run: npx cdktf synth --context env=${{ steps.env.outputs.env_name }}

      - name: Upload cdktf.out (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cdktf.out-${{ steps.env.outputs.env_name }}
          path: ${{ env.APP_ROOT }}/cdktf.out

      - name: Deploy ${{ steps.env.outputs.STACK_NAME }}
        working-directory: ${{ env.APP_ROOT }}
        run: npx cdktf deploy ${{ steps.env.outputs.STACK_NAME }} --context env=${{ steps.env.outputs.env_name }} --auto-approve

      - name: Print service endpoint(s)
        working-directory: ${{ env.APP_ROOT }}
        env:
          CTX_ENV: ${{ steps.env.outputs.env_name }}
        shell: bash
        run: |
          node scripts/print-ec2.cjs | tee ec2.txt
          {
            echo "### Service Endpoints (${{ steps.env.outputs.env_name }})"
            echo
            echo '```'
            cat ec2.txt
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

