name: CityTaster Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      DB_NAME: CityTasterDB

    steps:
      # 1. Checkout latest code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 4. Login to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 5. Debug AWS Account ID (should be masked)
      - name: Debug AWS_ACCOUNT_ID value
        run: |
          echo "Account ID is [${{ secrets.AWS_ACCOUNT_ID }}]"

      # 6. Build and push backend Docker image (from root context)
      - name: Build and push backend Docker image
        run: |
          docker buildx build \
            --push \
            --file deployment/Dockerfile.backend \
            -t "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/citytaster-backend:latest" \
            .

      # 7. Build and push frontend Docker image (from root context)
      - name: Build and push frontend Docker image
        run: |
          docker buildx build \
            --push \
            --file deployment/Dockerfile.frontend \
            -t "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/citytaster-frontend:latest" \
            .

      # 8. Sync data directory to S3
      - name: Sync data folder to S3
        run: |
          aws s3 sync ./data s3://${{ secrets.S3_BUCKET_NAME }}/data

      # 9. Deploy on EC2 via SSH with docker-compose
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd app || (mkdir app && cd app)
            aws s3 sync s3://${{ secrets.S3_BUCKET_NAME }}/data ./data
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
            docker-compose pull
            docker-compose up -d
            docker image prune -af

