name: CityTaster Deploy

on:
  push:
    branches: [main]           # Trigger CD on push to main
  workflow_dispatch:           # Allow manual deploy trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      DB_NAME: CityTasterDB

    steps:
      # Checkout latest code
      - name: Checkout code
        uses: actions/checkout@v4

      # Enable Docker Buildx for pushing to ECR
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Configure AWS access
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Login to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Debug: Output AWS Account ID (will be masked if set correctly)
      - name: Debug AWS_ACCOUNT_ID value
        run: |
          echo "Account ID is [${{ secrets.AWS_ACCOUNT_ID }}]"

      # Backend: Build and push Docker image to ECR
      - name: Build and push backend Docker image
        run: |
          docker buildx build \
            --push \
            --file deployment/Dockerfile.backend \
            -t "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/citytaster-backend:latest" \
            ./backend

      # Frontend: Build and push Docker image to ECR
      - name: Build and push frontend Docker image
        run: |
          docker buildx build \
            --push \
            --file deployment/Dockerfile.frontend \
            -t "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/citytaster-frontend:latest" \
            ./frontend

      # Sync data directory to S3
      - name: Sync data folder to S3
        run: |
          aws s3 sync ./data s3://${{ secrets.S3_BUCKET_NAME }}/data

      # Deploy on EC2 via SSH with docker-compose
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd app || (mkdir app && cd app)
            aws s3 sync s3://${{ secrets.S3_BUCKET_NAME }}/data ./data
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
            docker-compose pull
            docker-compose up -d
            docker image prune -af

